# process names are case-insensitive
# you can use 'master' to indicate the master channel, or a list of process names to create a group
slider_mapping:
  0: master
  1: steam.exe
  2: chrome.exe

# To control several processes with one slider use this format
#   2: 
#     - process1.exe
#     - process2.exe
#     - process3.exe


# recommend to leave this setting at its default value
process_refresh_frequency: 5

# settings for connecting to the arduino board
com_port: COM4 # Used by Arduino Uno
# com_port: COM11 # Used by Arduino Mega

baud_rate: 9600
